## Array Operations

In [1]:
import numpy as np

#### Arithematic operations

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [6]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [11]:
l = [10,20,30,40]
arr = np.array(l)

In [12]:
arr + 10

array([20, 30, 40, 50])

In [13]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Deep and Shallow copy

In [17]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a[4:6] * 10

array([50, 60])

In [23]:
a
b = a

In [24]:
b[0] = 99

In [25]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations

In [27]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [28]:
A

array([[1, 2],
       [3, 4]])

In [29]:
B

array([[5, 6],
       [7, 8]])

In [30]:
A * B

array([[ 5, 12],
       [21, 32]])

In [31]:
A @ B

array([[19, 22],
       [43, 50]])

In [32]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [33]:
A.T

array([[1, 3],
       [2, 4]])

## Advanced Array Manipulation

#### Stacking Array

In [34]:
A

array([[1, 2],
       [3, 4]])

In [35]:
B

array([[5, 6],
       [7, 8]])

In [36]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [37]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
a = np.vsplit(c,4)
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
