In [1]:
def hello():
    print("How are you")

In [2]:
hello()

How are you


In [4]:
import numpy as np

#### Basics Array Creations

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3,4.5]
a

[1, 2, 3, 4.5]

In [12]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# Array Generation function
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [21]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
# Random Generation Functions
np.random.rand(10)

array([0.39343264, 0.09602048, 0.59543691, 0.73468182, 0.6959469 ,
       0.88211639, 0.59647199, 0.50349918, 0.95185473, 0.41045499])

In [36]:
np.random.randn(10)

array([ 0.68826722, -0.43898678,  0.84792718, -0.45759381, -0.57551014,
        0.25691415,  0.19842151,  1.17407647,  0.00255333,  0.44429206])

In [43]:
np.random.randint(10,20,10)

array([14, 16, 18, 19, 15, 14, 14, 13, 17, 16], dtype=int32)

In [46]:
# Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.shape

(3, 3)

In [49]:
arr.size

9

In [50]:
arr.dtype

dtype('int64')

In [51]:
# Array Method
arr.min()

np.int64(1)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.sum()

np.int64(45)

In [55]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [56]:
arr.mean()

np.float64(5.0)

In [57]:
arr.std()

np.float64(2.581988897471611)

In [58]:
arr.argmax()

np.int64(8)

In [60]:
arr.argmin()

np.int64(0)

In [63]:
# Reshaping and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

#### Numpy indexing and slicing of vectors

In [68]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
arr[3::2]

array([14, 16, 18, 20])

In [77]:
arr[4]

np.int64(15)

In [78]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

#### Numpy Indexing and slicing of Matrix

In [81]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [82]:
arr[0]

array([1, 2, 3, 4, 5])

In [83]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [84]:
arr[5]

array([26, 27, 28, 29, 30])

In [91]:
arr[0,4]

np.int64(5)

In [92]:
arr[4,2]

np.int64(23)

In [95]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [100]:
slice = arr[3:6,3:6]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [102]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

#### Boolean Indexing

In [109]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [105]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [110]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])